package com.capg.rba.entities;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Entity
@Getter
@Setter
@ToString
@NoArgsConstructor
@ApiModel
@Table(name = "users")

@Inheritance(strategy = InheritanceType.JOINED)
public class User {

	@Id
	@TableGenerator(name = "Id_Gen", initialValue = 100, allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "Id_Gen")
	@ApiModelProperty(notes = "userId will be autogenerated", required = false, position = 1)
	private int userId;
	
	@NotNull(message = "password can not be null")
	@Pattern(regexp = ".{6}.*", message = "password should consist minimum six characters")
	@ApiModelProperty(notes = "password should consist of minimum six characters", example = "vision@4512", required = true, position = 2)
	private String password;
	
	@ApiModelProperty(notes = "value of role should be customer", example = "customer", required = false, position = 3)
	private String role;
	
	@NotNull(message = "mobile number can not be null")
	@Pattern(regexp = "(0/91)?[7-9][0-9]{9}", message = "Invalid mobile number")
	@ApiModelProperty(notes = "mobile number should be valid", example = "97658545256", required = true, position = 4)
	private String mobile;
	
	@NotNull(message = "email can not be null")
	@Pattern(regexp = "^([\\w-\\.]+){1,64}@([\\w&&[^_]]+){2,255}.[a-z]{2,}$", message = "Invalid email address")
	@ApiModelProperty(notes = "email should be valid", example = "lucky@gmail.com", required = true, position = 5)
	private String email;
	
	@NotBlank(message = "City can not be blank or null")
	@ApiModelProperty(notes = "city can not be null or blank", example = "mathura", required = true, position = 6)
	private String city;

}
